import assert from 'node:assert/strict';
import test from 'node:test';
import React, { useEffect } from 'react';
import { create } from '@react-three/test-renderer';
import { useThree } from '@react-three/fiber';
import { Matrix4, Vector3 } from 'three';
import { AmbientSystem } from '../src/components/world/AmbientSystem.tsx';
import { createSceneRuntime, world } from '../src/content/world.ts';
Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });
for (const quality of ['high', 'medium', 'low']) test(`local environment responses and pause at ${quality} quality`, async () => {
  const runtime = { current: createSceneRuntime() };
  let root;
  function Probe() { const get = useThree(state => state.get); useEffect(() => { root = get(); }, [get]); return null; }
  const render = paused => React.createElement(React.Fragment, null, React.createElement(Probe), React.createElement(AmbientSystem, { runtime, paused, quality }));
  const renderer = await create(render(false), { camera: { position: [13, 14, 30], fov: 43 } });
  const frames = async count => { for (let index = 0; index < count; index++) await renderer.advanceFrames(1, 1 / 60); };
  const scene = renderer.scene.instance;
  const grass = scene.getObjectByName('environment-grass');
  const clouds = scene.getObjectByName('environment-clouds');
  const motes = scene.getObjectByName('environment-distant-motes');
  const points = scene.children[0].children.find(object => object.isPoints);
  const matrix = new Matrix4();
  grass.getMatrixAt(0, matrix);
  const position = new Vector3().setFromMatrixPosition(matrix);
  runtime.current.pointerWorld = [position.x, 0, position.z];
  root.camera.lookAt(position); root.camera.updateMatrixWorld();
  runtime.current.hovered = 'work';
  await frames(10);
  assert.equal(runtime.current.plantInteraction, 0);
  assert.equal(runtime.current.cloudInteraction, 0);
  assert.equal(grass.material.uniforms.uPointerStrength.value, 0);
  assert.equal(points.material.opacity, .25);
  runtime.current.pointerActive = true;
  await frames(10);
  assert.equal(runtime.current.plantInteraction, 1);
  assert.ok(grass.material.uniforms.uPointerStrength.value > .5);
  assert.deepEqual(grass.material.uniforms.uFogRange.value.toArray(), [world.lighting.fogNear, world.lighting.fogFar]);
  const frozen = grass.material.uniforms.uPointerStrength.value;
  await renderer.update(render(true));
  runtime.current.pointerActive = false;
  runtime.current.elapsed = 10;
  await frames(20);
  assert.equal(grass.material.uniforms.uPointerStrength.value, frozen);
  assert.equal(runtime.current.plantInteraction, 1);
  await renderer.update(render(false));
  await frames(120);
  assert.ok(grass.material.uniforms.uPointerStrength.value < .000001);
  assert.equal(runtime.current.plantInteraction, 1);
  runtime.current.pointerWorld = [1000, 0, 1000];
  const centers = clouds.geometry.attributes.aCenter;
  const speed = clouds.geometry.attributes.aSpeed.getX(0);
  position.set((centers.getX(0) + runtime.current.elapsed * speed + 85) % 170 - 85, centers.getY(0), centers.getZ(0));
  root.camera.lookAt(position); root.camera.updateMatrixWorld();
  const beforeCloud = runtime.current.cloudInteraction;
  runtime.current.pointerActive = true;
  const shader = { uniforms: {}, vertexShader: '#include <project_vertex>' };
  clouds.material.onBeforeCompile(shader, null);
  await frames(10);
  assert.equal(runtime.current.cloudInteraction, beforeCloud + 1);
  assert.ok(shader.uniforms.uPointerStrength.value > .5);
  assert.equal(runtime.current.plantInteraction, 1);
  assert.equal(motes.material.uniforms.uPointer, undefined);
  assert.ok(motes.count <= 5);
  for (let index = 0; index < motes.count; index++) {
    motes.getMatrixAt(index, matrix);
    position.setFromMatrixPosition(matrix);
    assert.ok(position.y > 9 && position.z < -25);
    position.setFromMatrixScale(matrix);
    assert.ok(position.x >= .079 && position.x <= .221);
  }
  await renderer.unmount();
});
